# Generated by Django 4.1.2 on 2022-10-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='onwer',
            new_name='owner',
        ),
    ]
