# Generated by Django 4.1.2 on 2022-10-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_favorites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
